# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.7
_src_path: gh:algorandfoundation/algokit-python-template
author_email: camilo@algorand.foundation
author_name: Camilo Molano
contract_name: token_factory
deployment_language: python
preset_name: production
project_name: token_factory

